# Generated by Django 4.1.3 on 2022-11-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('slug', models.SlugField(max_length=200)),
                ('sku', models.CharField(blank=True, help_text='stock keeping unit', max_length=50, null=True, verbose_name='SKU')),
                ('parcode', models.ImageField(blank=True, null=True, upload_to='images/product-parcode')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='images/product-parcode')),
                ('stock_qty', models.FloatField(default=0, verbose_name='Stock Available Qty')),
                ('product_price', models.FloatField(default=0, verbose_name='Product Price')),
                ('sale_price', models.FloatField(default=0, verbose_name='Sale Price')),
                ('description_l', models.TextField(blank=True, help_text='Product long description', max_length=500, null=True, verbose_name='Product Description')),
                ('description_s', models.CharField(blank=True, help_text='Product short description', max_length=200, null=True, verbose_name='Product Description')),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=200)),
                ('code', models.CharField(max_length=100, verbose_name='Category Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
