# Generated by Django 4.1.3 on 2022-11-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Product Code'),
            preserve_default=False,
        ),
    ]
