# Generated by Django 4.1.3 on 2022-11-30 13:51

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=treewidget.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
            preserve_default=False,
        ),
    ]
