# Generated by Django 4.1.3 on 2022-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-images'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
