# Generated by Django 4.1.3 on 2022-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_discount_price_alter_variation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_l',
            field=models.TextField(blank=True, help_text='Category long description', max_length=500, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_s',
            field=models.CharField(blank=True, help_text='Category short description', max_length=200, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
