# Generated by Django 4.1.3 on 2022-12-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_size_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'ProductAttributes'},
        ),
    ]
