# Generated by Django 4.1.3 on 2022-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_productattribute_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Perfume SizeUnit',
            },
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Sizes'},
        ),
    ]
