# Generated by Django 4.1.3 on 2022-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_orderitem_item_variations'),
        ('inventory', '0016_size_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
