# Generated by Django 4.1.3 on 2022-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_variation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Product Specs or Attr'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sale_price',
            field=models.FloatField(default=0, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sku',
            field=models.CharField(blank=True, help_text='stock keeping unit', max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
