# Generated by Django 4.1.3 on 2022-12-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Product Attributes'},
        ),
    ]
