# Generated by Django 4.1.3 on 2022-12-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_productattribute_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='discount price'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(default=0, help_text='Item Cost', verbose_name='Item Cost'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Regular Price'),
        ),
    ]
