# Generated by Django 4.1.3 on 2022-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
