# Generated by Django 4.1.3 on 2022-11-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_user_username_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ie_customer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ie_employee',
            new_name='is_employee',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ie_supplier',
            new_name='is_supplier',
        ),
    ]
