# Generated by Django 4.1.3 on 2022-12-04 19:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Company Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Company Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Company LinkedIn'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Company Twitter'),
        ),
    ]
