# Generated by Django 4.1.3 on 2022-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_is_main_company_is_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designate the Company to be an Active Company', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Designate the Company to be the Main Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='Designate the Company to be Shipping', verbose_name='Shipping Company'),
        ),
    ]
