# Generated by Django 4.1.3 on 2022-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_is_active_alter_company_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
