# Generated by Django 4.1.3 on 2022-12-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('company', '0015_alter_currency_options_remove_currency_is_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
    ]
