# Generated by Django 4.1.3 on 2022-12-21 11:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shipping Zone')),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
            ],
        ),
    ]
