# Generated by Django 4.1.3 on 2022-12-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=50, verbose_name='Rate Name')),
                ('price', models.FloatField(default=0, verbose_name='Rate Price')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingzone')),
            ],
        ),
    ]
