# Generated by Django 4.1.3 on 2022-12-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_is_active_alter_company_is_main_and_more'),
        ('shipping', '0002_shoppingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingrate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
