# Generated by Django 4.1.3 on 2022-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shoppingrate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingrate',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Days'),
        ),
    ]
