# Generated by Django 4.1.3 on 2022-12-23 10:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shoppingrate_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='country',
            field=django_countries.fields.CountryField(max_length=26, multiple=True),
        ),
    ]
