# Generated by Django 4.1.3 on 2022-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_variations',
        ),
    ]
