# Generated by Django 4.1.3 on 2022-12-10 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_alter_productattribute_options'),
        ('sales', '0009_order_delivery_date_order_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfavourite',
            options={'verbose_name_plural': 'Client Favourite List'},
        ),
        migrations.AddField(
            model_name='customerfavourite',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='CustomerFavouriteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customerfavourite',
            name='items',
            field=models.ManyToManyField(to='sales.customerfavouriteitems'),
        ),
    ]
