# Generated by Django 4.1.3 on 2022-12-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_customerfavourite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_transit',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
