# Generated by Django 4.1.3 on 2022-12-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_order_order_transit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToPackOrder',
            fields=[
            ],
            options={
                'verbose_name_plural': 'orders To Pack',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.order',),
        ),
    ]
